# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b2ec9b0133c6f00e9fa7d37e8a6c829059850d7fead0727f5e884bb27a2a84dbfefc6df16298057736977ed377075567f9518449e53a2ed1aa0a1c023159aa

test:
  secret_key_base: 0235ebe882563ddaede68921b9754da34aa2269b51dc6ddb3fc2a94c58505eccced2a240844ed410b6d1f5fe905787878f07f28d70a7f10a2426a4b73e928973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
